title: あずま.いお
theme: minima
url: "https://enyuka.github.io"
baseurl: "/azuma-io"
locale: ja_JP

header_pages:
  - about.md

collections:
  articles:
    output: true
    permalink: /:collection/:name/

twitter:
  card: summary_large_image
  username: "edhazumanobuyuk"             
